### ISSUE TITLE
Deploying Azure Delta Lake does not work - Function Error

### ISSUE THREAD

**Issue by iBoonz** [microsoft/healthcare-apis-samples#53]
Hi when trying to deploy the Azure Delta Lake, I get a conflict with the function 

`{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"Failed\",\r\n        \"message\": \"Failed to download package.\\r\\nARM-MSDeploy Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (409) Conflict.\\r\\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\\r\\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\\r\\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\\r\\n   --- End of inner exception stack trace ---\\r\\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\r\\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\\r\\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\\r\\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__17.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__15.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__27.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__25.MoveNext()\\r\\n---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (409) Conflict.\\r\\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\\r\\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\\r\\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---\\r\\n'\"\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}`

![image](https://user-images.githubusercontent.com/2930374/205582617-a1cc65f1-fe32-4ccf-b57f-d433aff2e8e1.png)

**Comment by brucenelson6655** [comment]
Confirming the same issue : `{"code":"Failed","message":"Failed to download package.\r\nARM-MSDeploy Deploy Failed: 'System.AggregateException: One or more errors occurred. ---&gt; System.Net.WebException: The remote server returned an error: (409) Conflict.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.&lt;Download&gt;d__15.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadPackageAndSettings&gt;d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__25.MoveNext()\r\n---&gt; (Inner Exception #0) System.Net.WebException: The remote server returned an error: (409) Conflict.\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)&lt;---\r\n'"}`

Which then bubbles up the error :
 `
{"code":"DeploymentFailed","target":"/subscriptions/3f2e4d32-8e8d-46d6-82bc-5bb8d962328b/resourceGroups/brn-fhir-sample-testing/providers/Microsoft.Resources/deployments/Microsoft.Template-20230529195322","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/3f2e4d32-8e8d-46d6-82bc-5bb8d962328b/resourceGroups/brn-fhir-sample-testing/providers/Microsoft.Web/sites/fhirdlinbaaw56g23h2-fa/extensions/MSDeploy","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'failed'."}]}`

**Comment by fsanchez145** [comment]
I received the same error.  However, I noticed that [load-synthea-fhirdl5bwfqwiel6a2a0ahds] had a status of Created but didn't have a checkmark.

**Comment by fsanchez145** [comment]
I modified the code on line 165 from MSDeploy to ZipDeploy extension and the function was created.
Can someone make the necessary changes to it?
 {
            "type": "Microsoft.Web/sites/extensions",
            "apiVersion": "2022-03-01",
            "name": "[format('{0}/{1}', variables('functionAppName'), **'ZipDeploy'**)]",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', variables('functionAppName'))]",
                "[resourceId('Microsoft.Web/sites/config', variables('functionAppName'), 'appsettings')]"
            ],
            "properties": {
                "packageUri": "[parameters('packageUrl')]"
            },
            "metadata": {
                "description": "Deploy the FHIR to Analytics function app code to the function app"
            }
        },

**Comment by fsanchez145** [comment]
[
![Figure 09 - FHIR to Delta Lake Sample Environment - Custom Script](https://github.com/microsoft/healthcare-apis-samples/assets/114030198/49d8f73d-0ed0-4e78-8f8d-e1ae0dd45299)
]

**Comment by fsanchez145** [comment]
![Figure 10 - FHIR to Delta Lake Sample Environment - Custom Script](https://github.com/microsoft/healthcare-apis-samples/assets/114030198/ce2d293e-e8a5-4756-9e5d-ffdc065c4d35)

**Comment by evachen96** [comment]
Thank you for your interest in our repository. As of April 10, 2024, this repository is no longer being developed or maintained. We recommend that you use the new [Azure Health Data and AI Samples Repo](https://github.com/Azure-Samples/azure-health-data-and-ai-samples).
